[package]
name = "kgz10_proof_of_inclusion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-ec = "0.3.0"
ark-ff = "0.3.0"
ark-poly = "0.3.0"
ark-serialize = "0.3.0"
ark-std = "0.3.0"
ark-poly-commit = "0.3.0"
ark-bls12-381 = "0.3.0"
